services:
  teranga-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: https://api.talentsenegal.com/api
        VITE_KEYCLOAK_URL: https://auth.talentsenegal.com
        VITE_KEYCLOAK_REALM: terangaSenegal
        VITE_KEYCLOAK_CLIENT_ID: terangasenegal

    container_name: teranga-frontend

    ports:
      - "127.0.0.1:3000:80"

    restart: unless-stopped

    networks:
      - teranga-network


networks:
  teranga-network:
    external: true
    name: backend_teranga-network
