export const SECTEURS_ACTIVITE = [
    "Agriculture",
    "Agroalimentaire",
    "Architecture",
    "Assurance",
    "Banque",
    "BTP / Construction",
    "Commerce",
    "Communication",
    "Comptabilité",
    "Consulting",
    "Éducation",
    "Énergie",
    "Finance",
    "Hôtellerie",
    "Immobilier",
    "Industrie",
    "Informatique / IT",
    "Logistique",
    "Marketing",
    "Médias",
    "Mines",
    "ONG",
    "Pharmaceutique",
    "Ressources Humaines",
    "Santé",
    "Sécurité",
    "Télécommunications",
    "Tourisme",
    "Transport",
    "Administration publique",
    "Autre",
] as const;